baseURL = "https://example.org/"
languageCode = "en-us"
title = "Drew Council"
theme = "typo"

[caches.images]
dir = ":cacheDir/images"

[markup.highlight]
style = "catppuccin-mocha"

[params]
# Meta description
description = ""
# Appearance settings
theme = "dark"
colorPalette = "catpuccin"
hideHeader = false
# Intro on main page, content is markdown
homeIntroTitle = "Hi!"
homeIntroContent = """
### Hello
test 123
"""
# Collection to display on home
homeCollectionTitle = "Posts"
homeCollection = "posts"
# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = "Jan 2 2006"

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "github"
url = "https://github.com/user"

[taxonomies]
tag = "tags"
