baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Drew Council'
theme = 'typo'

[caches.images]
dir = ':cacheDir/images'

[markup.highlight]
style = 'catppuccin-mocha'

[params]
colorPalette = 'catpuccin'
